{% set name = "terraform-ls" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/terraform-ls/archive/v{{ version }}.tar.gz
  sha256: 021340fa9b317d90d085ab13cfeaa7c0b802fda0ac03a8bd4e467579f909cd54

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - terraform-ls --help

about:
  home: https://github.com/hashicorp/terraform-ls
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Terraform Language Server
  dev_url: https://github.com/hashicorp/terraform-ls

extra:
  recipe-maintainers:
    - danielnachun
