schema_version: 1

context:
  version: "0.38.4"

package:
  name: terraform-ls
  version: ${{ version }}

source:
  url: https://github.com/hashicorp/terraform-ls/archive/v${{ version }}.tar.gz
  sha256: 698968b3606c422750fedd9d8a038ca3d0b7f57d7503d7ee60eade56dfb3d31a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - terraform-ls --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Terraform Language Server
  homepage: https://github.com/hashicorp/terraform-ls
  repository: https://github.com/hashicorp/terraform-ls

extra:
  recipe-maintainers:
    - danielnachun
