schema_version: 1

context:
  version: "0.38.5"

package:
  name: terraform-ls
  version: ${{ version }}

source:
  url: https://github.com/hashicorp/terraform-ls/archive/v${{ version }}.tar.gz
  sha256: 376188f6e0d2f1454e4144a09e32d0de2a42ef97778f0d500c2813b127f7ab9c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - terraform-ls --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Terraform Language Server
  homepage: https://github.com/hashicorp/terraform-ls
  repository: https://github.com/hashicorp/terraform-ls

extra:
  recipe-maintainers:
    - danielnachun
