schema_version: 1

context:
  version: "0.38.8"

package:
  name: terraform-ls
  version: ${{ version }}

source:
  url: https://github.com/hashicorp/terraform-ls/archive/v${{ version }}.tar.gz
  sha256: 1d2e725e49f08150ac4f9d3fab4961d56dde7f9f62922ce0ccdf93feb408c24c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - terraform-ls --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Terraform Language Server
  homepage: https://github.com/hashicorp/terraform-ls
  repository: https://github.com/hashicorp/terraform-ls

extra:
  recipe-maintainers:
    - danielnachun
