schema_version: 1

context:
  version: "0.39.0"

package:
  name: terraform-ls
  version: ${{ version }}

source:
  url: https://github.com/hashicorp/terraform-ls/archive/v${{ version }}.tar.gz
  sha256: 5a4fdd3e2a4fcf78b9d5e48c1f0a50d00a948f06d67f639f4a6217630eac396a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - terraform-ls --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Terraform Language Server
  homepage: https://github.com/hashicorp/terraform-ls
  repository: https://github.com/hashicorp/terraform-ls

extra:
  recipe-maintainers:
    - danielnachun
